### ISSUE TITLE
inconsistent index name generated between tenanted schema create via migrate and Tenant.create

### ISSUE THREAD

**Issue by wkempterGit** [dceballos/roomer#3]
I added a new table (and model) along with a unique index to the tenanted schema via rake roomer:tenanted:migrate and all went well. However, if after the migration, when I issue Tenant.create it fails with the following error:

-- add_index("corporate_advertisers", ["company_id"], {:name=>"company_id", :unique=>true})
ActiveRecord::StatementInvalid: PGError: ERROR:  relation "company_id" already exists
: CREATE UNIQUE INDEX "company_id" ON "poindexter"."corporate_advertisers" ("company_id")

The problem appears to be due to inconsistencies in the output of the schema creation when done via tenant record creation, specifically the generated name of the index. 

via migrate:

CREATE UNIQUE INDEX "index_wendy.corporate_advertisers_on_company_id" ON "wendy"."corporate_advertisers" ("company_id")

via Tenant.create!:

CREATE UNIQUE INDEX "company_id" ON "poindexter"."corporate_advertisers" ("company_id")

In a given postgres namespace (schema) you can not have two indexes with the same name, and as it happens when the schema is created via the Tenant.create two of different add_index statements are resolving to the same name, they are:

  add_index "addresses", ["company_id", "name"], :name => "company_id", :unique => true

  add_index :corporate_advertisers, :company_id, :unique => true

For whatever reason the index name generated by Tenant.create is way different from the one generated via migrate. I also noticed that if I rollback the migration, then change the add_index statement in the migration file to:

  add_index :corporate_advertisers, :company_id, :unique => true, :name => 'corporate_advertisers_company_id'

Then run the migration, the index name is created as specified above. However, Tenant.create will still try and create the index with the name 'company_id' and ignores the :name option.

After doing a bit of digging, I noticed that in the /schemas/tenanted_schema.rb file the add_index statement listed as:

  add_index "corporate_advertisers", ["company_id"], :name => "company_id", :unique => true

event though I explicitly specified the :name option in the migration file. I did find that I can manually change the :name option in tenanted_schema.rb to match what was in the migration rb and that temporarily fixes the problem, but that change gets overwritten whenever I run a migration.

**Comment by dceballos** [comment]
solved in e5d489fda8154c150fe49ef8378757700e3b8d7e
